version: '3.9'

services:
  database:
    container_name: database
    image: postgres:14-alpine3.15
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - todo_net
    tty: true
    restart: always
  app:
    container_name: app
    build:
      context: ./server
      dockerfile: ./Dockerfile
    working_dir: /usr/src/app  
    ports:
      - ${PORT}:${PORT}
      - '9229:9229'
    volumes:
      - .:/app
      - ignore:/usr/src/app/node_modules/
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - todo_net
    restart: always

volumes:
  pgdata:
  ignore:

networks:
  todo_net:
    driver: bridge

