version: '3.9'

services:
  main:
    container_name: main
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:${PORT}
      - '9229:9229'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - todo_net
    restart: unless-stopped
  database:
    container_name: database
    image: postgres:14-alpine3.15
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - todo_net
    tty: true
    restart: unless-stopped

volumes:
  pgdata:
  server:

networks:
  todo_net:
    driver: bridge