version: '3.9'

services:
  app:
    container_name: app
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
      - '9229:9229'
    volumes:
      - ./:/app/
    env_file:
      - ./server/.env
    depends_on:
      - database
    command: npm run start:dev
    restart: always
  database:
    container_name: database
    image: postgres:14-alpine3.15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todo_db
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: null